#Prevent batch jobs from starting automatically
spring:
  batch:
    job:
      enabled: false

  # The DB Connection to In-Memory DB. Actually you don't need this configuration, they are all in the default configuration.
  # I just put it here to show you how to configure the DB for Batch job. If you comment out the datasource block, the could should still run fine.
  datasource:
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    url: jdbc:hsqldb:mem:myDb
    username: sa
    password: sa
